### ISSUE TITLE
External temperature sensor

### ISSUE THREAD

**Issue by bearpawmaxim** [paveldn/ESP32-S0WD-Haier#6]
Is it possible(read: does the protocol has support) to supply an external temperature value for the AC module?
Thanks!

**Comment by paveldn** [comment]
Hi @bearpawmaxim ,

No this is not possible. A control/status packet has two parts: settings and sensors but only the first part you can use when sending commands to AC everything else will be ignored.

**Comment by bearpawmaxim** [comment]
Ah, pity.. 
Thanks! 
Closing this.
