### ISSUE TITLE
Display switch not working smartAir2 protocol

### ISSUE THREAD

**Issue by TyzzyT** [paveldn/ESP32-S0WD-Haier#8]
When I added the template switch for the display, the display will stay on no matter if I turn the switch on or turn the switch off. I hear the beep but the display doesn't turn on or off.
The strange thing is. When I remove the display template switch, the display is always off. So my workaround for now is to remove the template switch, which will disable the screen and I'm happy now :-)

YAML config:
```
esphome:
  name: "Airco livingroom"
  platform: ESP8266
  board: d1_mini
  friendly_name: "Airco livingroom"


external_components:
# Note: this may not be needed if the pull request has been merged.
# Check https://github.com/esphome/esphome/pull/4521 for current status.
  - source: github://pr#4521
    components: [haier]
    refresh: 1h

uart:
  baud_rate: 9600
  tx_pin: 1
  rx_pin: 3
  id: ac_port

climate:
  - platform: haier
    id: airco
    protocol: smartair2
    name: Airco livingroom
    uart_id: ac_port
    visual:
      min_temperature: 16 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
```

**Comment by paveldn** [comment]
Hi @TyzzyT ,

Yes, it looks like smartair2 ACs behave differently with display in comparison to hOn ACs. I will take a look at this issue and will try to fix it.

**Comment by paveldn** [comment]
@TyzzyT 
Can you please check smartair2_test  branch https://github.com/paveldn/ESP32-S0WD-Haier/tree/smartair2_test ?
It should solve the issue with the display.
Just make your external_components section like this:

```
external_components:
  source: github://paveldn/ESP32-S0WD-Haier@smartair2_test
```

**Comment by TyzzyT** [comment]
Just tested and can confirm this working. Great job!

**Comment by paveldn** [comment]
You are welcome. Thanks for testing!

**Comment by TyzzyT** [comment]
Sorry, off topic. But, is there anything I can do to also make the beeper switch work with smartair2 protocol?

**Comment by paveldn** [comment]
We can try. I can make a test version for you will let me know what is not working. I will let you know when it will be ready.

**Comment by paveldn** [comment]
@TyzzyT Can you please try the latest commit on the same branch? Let me know if it worked. It is possible that beep off will not work for IR remote commands only for commands from esphome (at least that is how it worked for hOn).

**Comment by TyzzyT** [comment]
Hey,
I see that I'm to late and you already changed beeper to sleep/health mode. I have flashed the ESP8266 with the new config and will test it out. I'll let you know the outcome in the next few hours.

**Comment by TyzzyT** [comment]
Allright, health mode it working as expected!
I'm not so sure if boost/sleep mode is working for me. I can change the values, but don't see anything changing. The AC is beeping, but there is not difference in airflow or power usage.

**Comment by paveldn** [comment]
Yes, I will include Health in the main branch as for boost/ sleep, it probably will need additional testing. Thanks.
